from sqlalchemy import Boolean, Column, Float, ForeignKey, Index, Integer, MetaData, String, Table, Text, false, text, true
from sqlalchemy.types import JSON

metadata = MetaData()
json_type = JSON(none_as_null=True)

jobs = Table(
    "jobs",
    metadata,
    Column("id", String, primary_key=True),
    Column("status", String, nullable=False),
    Column("request_input", json_type, nullable=False),
    Column("workspace_id", String),
    Column("content_plan_item_id", String),
    Column("origin_type", String),
    Column("retry_count", Integer, nullable=False, server_default=text("0")),
    Column("last_error", Text),
    Column("last_attempt_at", String),
    Column("human_review_required", Boolean, nullable=False, server_default=true()),
    Column("wordpress_post_id", String),
    Column("wordpress_edit_url", Text),
    Column("wordpress_public_url", Text),
    Column("wordpress_status", String),
    Column("wordpress_draft_created_at", String),
    Column("wordpress_connector_site_url", Text),
    Column("wordpress_publish_error", Text),
    Column("wordpress_publish_attempted_at", String),
    Column("wordpress_draft_updated_at", String),
    Column("last_wordpress_sync_at", String),
    Column("seo_title", Text),
    Column("seo_description", Text),
    Column("seo_focus_keyword", String),
    Column("seo_canonical_url", Text),
    Column("seo_robots", String),
    Column("seo_schema_type", String),
    Column("seo_generated_at", String),
    Column("seo_synced_at", String),
    Column("seo_last_error", Text),
    Column("rank_math_score", Float),
    Column("recommended_slug", String),
    Column("seo_manually_edited", Boolean, nullable=False, server_default=false()),
    Column("suggested_featured_image_alt", Text),
    Column("suggested_inline_image_alt", Text),
    Column("seo_optimized_at", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
)

artifacts = Table(
    "artifacts",
    metadata,
    Column("id", String, primary_key=True),
    Column("job_id", String, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("artifact_type", String, nullable=False),
    Column("content_json", json_type),
    Column("content_text", Text),
    Column("provider", String),
    Column("model", String),
    Column("token_input", Integer),
    Column("token_output", Integer),
    Column("estimated_cost", Float),
    Column("created_at", String, nullable=False),
    Index("idx_artifacts_job_type", "job_id", "artifact_type"),
)

job_logs = Table(
    "job_logs",
    metadata,
    Column("id", String, primary_key=True),
    Column("job_id", String, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("level", String, nullable=False),
    Column("step", String, nullable=False),
    Column("message", Text, nullable=False),
    Column("context_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_job_logs_job_id", "job_id"),
)

analysis_jobs = Table(
    "analysis_jobs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String),
    Column("website_url", Text, nullable=False),
    Column("competitor_urls_json", json_type, nullable=False),
    Column("status", String, nullable=False),
    Column("max_pages_per_site", Integer, nullable=False),
    Column("error_message", Text),
    Column("summary", Text),
    Column("prompt", Text),
    Column("raw_response_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_analysis_jobs_created_at", "created_at"),
)

analysis_pages = Table(
    "analysis_pages",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("source_type", String, nullable=False),
    Column("source_url", Text, nullable=False),
    Column("page_url", Text, nullable=False),
    Column("title", Text),
    Column("meta_description", Text),
    Column("h1_json", json_type),
    Column("h2_json", json_type),
    Column("h3_json", json_type),
    Column("canonical_url", Text),
    Column("extracted_links_json", json_type),
    Column("navigation_links_json", json_type),
    Column("questions_json", json_type),
    Column("entities_json", json_type),
    Column("body_sample", Text),
    Column("error_message", Text),
    Column("created_at", String, nullable=False),
    Index("idx_analysis_pages_job_id", "analysis_job_id"),
)

analysis_suggestions = Table(
    "analysis_suggestions",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("title", Text, nullable=False),
    Column("target_keyword", Text, nullable=False),
    Column("product_name", Text, nullable=False),
    Column("product_url", Text, nullable=False),
    Column("reason", Text),
    Column("confidence", String),
    Column("status", String, nullable=False),
    Column("generated_job_id", String, ForeignKey("jobs.id", ondelete="SET NULL")),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_analysis_suggestions_job_id", "analysis_job_id"),
)

audience_profiles = Table(
    "audience_profiles",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False),
    Column("description", Text),
    Column("audience_type", String),
    Column("expertise_level", String),
    Column("confidence", Float),
    Column("commercial_intent", Float),
    Column("research_intent", Float),
    Column("concerns_json", json_type),
    Column("recurring_questions_json", json_type),
    Column("preferred_content_types_json", json_type),
    Column("authority_topics_json", json_type),
    Column("related_entities_json", json_type),
    Column("related_clusters_json", json_type),
    Column("source_signals_json", json_type),
    Column("manual_override", Boolean, nullable=False, server_default=false()),
    Column("status", String, nullable=False, server_default=text("'inferred'")),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_audience_profiles_job", "analysis_job_id"),
)

opportunity_clusters = Table(
    "opportunity_clusters",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False),
    Column("description", Text),
    Column("parent_cluster_id", String),
    Column("entities_json", json_type),
    Column("source_terms_json", json_type),
    Column("confidence", Float),
    Column("authority_value", Float),
    Column("seo_value", Float),
    Column("editorial_value", Float),
    Column("geo_value", Float),
    Column("opportunity_count", Integer, nullable=False, server_default=text("0")),
    Column("primary_audiences_json", json_type),
    Column("audience_overlap_json", json_type),
    Column("pillar_candidate", Boolean, nullable=False, server_default=false()),
    Column("semantic_authority_role", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_opportunity_clusters_job", "analysis_job_id"),
)

opportunities = Table(
    "opportunities",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("cluster_id", String, ForeignKey("opportunity_clusters.id", ondelete="SET NULL")),
    Column("title", Text, nullable=False),
    Column("target_keyword", Text, nullable=False),
    Column("product_name", Text, nullable=False),
    Column("product_url", Text, nullable=False),
    Column("opportunity_type", String),
    Column("search_intent", String),
    Column("funnel_stage", String),
    Column("content_role", String),
    Column("primary_audience_id", String, ForeignKey("audience_profiles.id", ondelete="SET NULL")),
    Column("secondary_audience_ids_json", json_type),
    Column("audience_rationale", Text),
    Column("expertise_level", String),
    Column("confidence", Float),
    Column("scores_json", json_type),
    Column("related_products_json", json_type),
    Column("related_keywords_json", json_type),
    Column("related_entities_json", json_type),
    Column("authority_graph_node_ids_json", json_type),
    Column("relationship_ids_json", json_type),
    Column("rationale", Text),
    Column("source_type", String, nullable=False, server_default=text("'inferred'")),
    Column("evidence_summary", Text),
    Column("needs_verification", Boolean, nullable=False, server_default=true()),
    Column("evidence_items_json", json_type),
    Column("competitor_references_json", json_type),
    Column("suggested_article_length", Integer),
    Column("suggested_structure_json", json_type),
    Column("suggested_media_json", json_type),
    Column("suggested_internal_links_json", json_type),
    Column("cta_strategy", Text),
    Column("status", String, nullable=False, server_default=text("'suggested'")),
    Column("generated_job_id", String, ForeignKey("jobs.id", ondelete="SET NULL")),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_opportunities_job", "analysis_job_id"),
    Index("idx_opportunities_cluster", "cluster_id"),
    Index("idx_opportunities_primary_audience", "primary_audience_id"),
    Index("idx_opportunities_type_status", "opportunity_type", "status"),
)

opportunity_audiences = Table(
    "opportunity_audiences",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("opportunity_id", String, ForeignKey("opportunities.id", ondelete="CASCADE"), nullable=False),
    Column("audience_id", String, ForeignKey("audience_profiles.id", ondelete="CASCADE"), nullable=False),
    Column("role", String, nullable=False),
    Column("rationale", Text),
    Column("created_at", String, nullable=False),
    Index("idx_opportunity_audiences_opportunity", "opportunity_id"),
    Index("idx_opportunity_audiences_audience", "audience_id"),
)

authority_graph_nodes = Table(
    "authority_graph_nodes",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("node_type", String, nullable=False),
    Column("label", Text, nullable=False),
    Column("description", Text),
    Column("confidence", Float),
    Column("source_signals_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_authority_graph_nodes_job", "analysis_job_id"),
    Index("idx_authority_graph_nodes_type", "node_type"),
)

authority_graph_edges = Table(
    "authority_graph_edges",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("source_node_id", String, ForeignKey("authority_graph_nodes.id", ondelete="CASCADE"), nullable=False),
    Column("target_node_id", String, ForeignKey("authority_graph_nodes.id", ondelete="CASCADE"), nullable=False),
    Column("relationship_type", String, nullable=False),
    Column("strength", Float),
    Column("rationale", Text),
    Column("created_at", String, nullable=False),
    Index("idx_authority_graph_edges_job", "analysis_job_id"),
    Index("idx_authority_graph_edges_source", "source_node_id"),
)

opportunity_relationships = Table(
    "opportunity_relationships",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("parent_id", String, ForeignKey("opportunities.id", ondelete="CASCADE"), nullable=False),
    Column("child_id", String, ForeignKey("opportunities.id", ondelete="CASCADE"), nullable=False),
    Column("relationship_type", String, nullable=False),
    Column("strength", Float),
    Column("rationale", Text),
    Column("source", String),
    Column("created_at", String, nullable=False),
    Index("idx_opportunity_relationships_parent", "parent_id"),
    Index("idx_opportunity_relationships_child", "child_id"),
)

opportunity_recommendations = Table(
    "opportunity_recommendations",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("analysis_job_id", String),
    Column("source_type", String, nullable=False),
    Column("source_id", String),
    Column("topic", Text, nullable=False),
    Column("title", Text, nullable=False),
    Column("target_keyword", Text),
    Column("action", String, nullable=False),
    Column("priority", String, nullable=False),
    Column("confidence", Float),
    Column("score", Float),
    Column("business_relevance", Float),
    Column("niche_relevance", Float),
    Column("trend_relevance", Float),
    Column("coverage_gap", Float),
    Column("freshness", Float),
    Column("audience_relevance", Float),
    Column("competitor_gap", Float),
    Column("cannibalization_risk", Float),
    Column("reasons_json", json_type),
    Column("evidence_json", json_type),
    Column("related_opportunity_id", String),
    Column("related_content_id", String),
    Column("trend_signal_id", String),
    Column("coverage_id", String),
    Column("status", String, nullable=False, server_default=text("'active'")),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_opportunity_recommendations_workspace", "workspace_id"),
    Index("idx_opportunity_recommendations_action", "workspace_id", "action", "priority"),
    Index("idx_opportunity_recommendations_status", "workspace_id", "status"),
)

workspace_wordpress_connector = Table(
    "workspace_wordpress_connector",
    metadata,
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), primary_key=True),
    Column("connector_enabled", Boolean, nullable=False, server_default=false()),
    Column("wordpress_base_url", Text),
    Column("trendplot_site_id", String),
    Column("trendplot_shared_secret", Text),
    Column("last_connection_status", String),
    Column("last_connection_checked_at", String),
    Column("last_connection_error", Text),
    Column("connector_plugin_version", String),
    Column("connector_api_version", String),
    Column("active_environment", String, nullable=False, server_default=text("'staging'")),
    Column("environments_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
)

manual_recommendations = Table(
    "manual_recommendations",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("source", String, nullable=False, server_default=text("'manual'")),
    Column("status", String, nullable=False),
    Column("raw_headline", Text, nullable=False),
    Column("raw_notes", Text),
    Column("enhanced_headline", Text),
    Column("abstract", Text),
    Column("search_intent", String),
    Column("content_type", String),
    Column("recommendation_type", String, nullable=False, server_default=text("'create'")),
    Column("related_products_json", json_type),
    Column("related_topics_json", json_type),
    Column("target_audience", Text),
    Column("priority_reason", Text),
    Column("safety_notes_json", json_type),
    Column("enrichment_json", json_type),
    Column("duplicate_warnings_json", json_type),
    Column("recommendation_id", String),
    Column("created_by", String),
    Column("ai_enriched_at", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_manual_recommendations_workspace", "workspace_id", "status"),
)

opportunity_campaigns = Table(
    "opportunity_campaigns",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False),
    Column("audience_ids_json", json_type),
    Column("cadence", String),
    Column("publish_policy", String),
    Column("status", String, nullable=False, server_default=text("'draft'")),
    Column("plan_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_opportunity_campaigns_job", "analysis_job_id"),
)

opportunity_campaign_items = Table(
    "opportunity_campaign_items",
    metadata,
    Column("id", String, primary_key=True),
    Column("campaign_id", String, ForeignKey("opportunity_campaigns.id", ondelete="CASCADE"), nullable=False),
    Column("opportunity_id", String, ForeignKey("opportunities.id", ondelete="CASCADE"), nullable=False),
    Column("sequence_index", Integer, nullable=False),
    Column("role", String),
    Column("notes", Text),
    Column("created_at", String, nullable=False),
    Index("idx_opportunity_campaign_items_campaign", "campaign_id"),
)

analysis_intelligence_artifacts = Table(
    "analysis_intelligence_artifacts",
    metadata,
    Column("id", String, primary_key=True),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("artifact_type", String, nullable=False),
    Column("content_json", json_type),
    Column("provider", String),
    Column("created_at", String, nullable=False),
    Index("idx_analysis_intelligence_job_type", "analysis_job_id", "artifact_type"),
)

analyze_flow_runs = Table(
    "analyze_flow_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="SET NULL")),
    Column("parent_run_id", String),
    Column("rerun_type", String),
    Column("website_url", Text, nullable=False),
    Column("run_label", Text),
    Column("overall_status", String, nullable=False, server_default=text("'queued'")),
    Column("state_json", json_type, nullable=False),
    Column("request_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Column("completed_at", String),
    Index("idx_analyze_flow_runs_created", "created_at"),
    Index("idx_analyze_flow_runs_workspace", "workspace_id"),
)

autopilot_workspaces = Table(
    "autopilot_workspaces",
    metadata,
    Column("id", String, primary_key=True),
    Column("name", Text, nullable=False),
    Column("website_url", Text, nullable=False),
    Column("mode", String, nullable=False, server_default=text("'manual_review'")),
    Column("status", String, nullable=False, server_default=text("'setup'")),
    Column("cadence", String, nullable=False, server_default=text("'weekly'")),
    Column("user_context", Text),
    Column("settings_json", json_type),
    Column("last_analysis_job_id", String),
    Column("last_content_plan_id", String),
    Column("last_reassessment_id", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_autopilot_workspaces_status", "status"),
    Index("idx_autopilot_workspaces_url", "website_url"),
)

workspace_connections = Table(
    "workspace_connections",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("connection_type", String, nullable=False),
    Column("status", String, nullable=False, server_default=text("'not_connected'")),
    Column("capabilities_json", json_type),
    Column("metadata_json", json_type),
    Column("last_checked_at", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_workspace_connections_workspace", "workspace_id"),
    Index("idx_workspace_connections_type", "connection_type"),
)

site_understanding_snapshots = Table(
    "site_understanding_snapshots",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="SET NULL")),
    Column("summary", Text),
    Column("detected_niche", Text),
    Column("niche_confidence", Float),
    Column("products_services_json", json_type),
    Column("audiences_json", json_type),
    Column("competitors_json", json_type),
    Column("brand_voice_json", json_type),
    Column("trust_topics_json", json_type),
    Column("content_gaps_json", json_type),
    Column("vertical_detection_json", json_type),
    Column("source_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_site_understanding_workspace", "workspace_id"),
    Index("idx_site_understanding_analysis", "analysis_job_id"),
)

workspace_niche_profiles = Table(
    "workspace_niche_profiles",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("primary_niche", Text),
    Column("secondary_niches_json", json_type),
    Column("known_entities_json", json_type),
    Column("known_products_json", json_type),
    Column("known_categories_json", json_type),
    Column("known_audiences_json", json_type),
    Column("common_terminology_json", json_type),
    Column("confidence", Float),
    Column("sources_json", json_type),
    Column("last_updated", String, nullable=False),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_workspace_niche_profiles_workspace", "workspace_id"),
)

competitor_snapshots = Table(
    "competitor_snapshots",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="SET NULL")),
    Column("competitor_url", Text, nullable=False),
    Column("summary", Text),
    Column("topics_json", json_type),
    Column("products_services_json", json_type),
    Column("content_formats_json", json_type),
    Column("gap_notes_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_competitor_snapshots_workspace", "workspace_id"),
)

trend_signals = Table(
    "trend_signals",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="SET NULL")),
    Column("run_id", String),
    Column("query_id", String),
    Column("trend_topic", Text, nullable=False),
    Column("query", Text),
    Column("source_type", String, nullable=False),
    Column("source_provider", String),
    Column("confidence", Float),
    Column("freshness_score", Float),
    Column("trend_velocity", Float),
    Column("niche_relevance", Float),
    Column("audience_relevance", Float),
    Column("business_relevance", Float),
    Column("opportunity_score", Float),
    Column("why_it_matters", Text),
    Column("recommended_angle", Text),
    Column("recommended_format", String),
    Column("evergreen_classification", String),
    Column("expires_at", String),
    Column("content_opportunity_id", String, ForeignKey("opportunities.id", ondelete="SET NULL")),
    Column("needs_verification", Boolean, nullable=False, server_default=true()),
    Column("evidence_items_json", json_type),
    Column("raw_signal_json", json_type),
    Column("status", String, nullable=False, server_default=text("'active'")),
    Column("created_at", String, nullable=False),
    Index("idx_trend_signals_workspace", "workspace_id"),
    Index("idx_trend_signals_topic", "trend_topic"),
)

trend_discovery_runs = Table(
    "trend_discovery_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="SET NULL")),
    Column("status", String, nullable=False),
    Column("summary", Text),
    Column("context_json", json_type),
    Column("provider_status_json", json_type),
    Column("warnings_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_trend_discovery_runs_workspace", "workspace_id"),
    Index("idx_trend_discovery_runs_analysis", "analysis_job_id"),
)

trend_discovery_queries = Table(
    "trend_discovery_queries",
    metadata,
    Column("id", String, primary_key=True),
    Column("run_id", String, ForeignKey("trend_discovery_runs.id", ondelete="CASCADE"), nullable=False),
    Column("query", Text, nullable=False),
    Column("query_type", String),
    Column("target_entity", Text),
    Column("target_audience", Text),
    Column("reason", Text),
    Column("created_at", String, nullable=False),
    Index("idx_trend_discovery_queries_run", "run_id"),
)

demand_observation_runs = Table(
    "demand_observation_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("provider", String, nullable=False),
    Column("source_type", String, nullable=False),
    Column("status", String, nullable=False),
    Column("started_at", String, nullable=False),
    Column("completed_at", String),
    Column("date_start", String),
    Column("date_end", String),
    Column("rows_fetched", Integer, nullable=False, server_default=text("0")),
    Column("rows_persisted", Integer, nullable=False, server_default=text("0")),
    Column("warnings_json", json_type),
    Column("error_message", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_demand_observation_runs_workspace", "workspace_id", "created_at"),
    Index("idx_demand_observation_runs_provider", "workspace_id", "provider", "status"),
)

demand_observations = Table(
    "demand_observations",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("demand_observation_runs.id", ondelete="CASCADE")),
    Column("provider", String, nullable=False),
    Column("source_type", String, nullable=False),
    Column("observed_at", String, nullable=False),
    Column("date_start", String),
    Column("date_end", String),
    Column("query", Text),
    Column("page_url", Text),
    Column("topic", Text),
    Column("entity", Text),
    Column("country", String),
    Column("device", String),
    Column("impressions", Float),
    Column("clicks", Float),
    Column("ctr", Float),
    Column("position", Float),
    Column("normalized_demand_score", Float),
    Column("normalized_opportunity_score", Float),
    Column("freshness_score", Float),
    Column("confidence", Float),
    Column("trend_signal_id", String, ForeignKey("trend_signals.id", ondelete="SET NULL")),
    Column("opportunity_id", String, ForeignKey("opportunities.id", ondelete="SET NULL")),
    Column("coverage_id", String, ForeignKey("content_coverage.id", ondelete="SET NULL")),
    Column("published_content_id", String, ForeignKey("published_content.id", ondelete="SET NULL")),
    Column("raw_payload_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_demand_observations_workspace_observed", "workspace_id", "observed_at"),
    Index("idx_demand_observations_provider", "workspace_id", "provider", "source_type"),
    Index("idx_demand_observations_query", "workspace_id", "query"),
    Index("idx_demand_observations_page", "workspace_id", "page_url"),
    Index("idx_demand_observations_opportunity", "workspace_id", "normalized_opportunity_score"),
    Index("idx_demand_observations_run", "run_id"),
)

market_intelligence_runs = Table(
    "market_intelligence_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("status", String, nullable=False),
    Column("started_at", String, nullable=False),
    Column("completed_at", String),
    Column("signals_fetched", Integer, nullable=False, server_default=text("0")),
    Column("signals_persisted", Integer, nullable=False, server_default=text("0")),
    Column("clusters_created", Integer, nullable=False, server_default=text("0")),
    Column("candidates_created", Integer, nullable=False, server_default=text("0")),
    Column("warnings_json", json_type),
    Column("error_message", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_market_intelligence_runs_workspace", "workspace_id", "created_at"),
)

market_signals = Table(
    "market_signals",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("market_intelligence_runs.id", ondelete="CASCADE")),
    Column("provider", String, nullable=False),
    Column("source", String, nullable=False),
    Column("signal_type", String, nullable=False),
    Column("topic", Text),
    Column("entity", Text),
    Column("audience", Text),
    Column("market_scope", String),
    Column("language", String),
    Column("country", String),
    Column("confidence", Float),
    Column("freshness", Float),
    Column("velocity", Float),
    Column("novelty", Float),
    Column("relevance", Float),
    Column("evidence_count", Integer, nullable=False, server_default=text("1")),
    Column("source_url", Text),
    Column("observed_at", String, nullable=False),
    Column("raw_payload_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_market_signals_workspace_observed", "workspace_id", "observed_at"),
    Index("idx_market_signals_provider", "workspace_id", "provider", "signal_type"),
    Index("idx_market_signals_topic", "workspace_id", "topic"),
    Index("idx_market_signals_run", "run_id"),
)

market_signal_evidence = Table(
    "market_signal_evidence",
    metadata,
    Column("id", String, primary_key=True),
    Column("signal_id", String, ForeignKey("market_signals.id", ondelete="CASCADE"), nullable=False),
    Column("evidence_type", String, nullable=False),
    Column("title", Text),
    Column("url", Text),
    Column("snippet", Text),
    Column("source_name", Text),
    Column("published_at", String),
    Column("metric_name", String),
    Column("metric_value", Float),
    Column("confidence", Float),
    Column("raw_payload_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_market_signal_evidence_signal", "signal_id"),
)

market_topic_clusters = Table(
    "market_topic_clusters",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("market_intelligence_runs.id", ondelete="CASCADE")),
    Column("topic", Text, nullable=False),
    Column("entities_json", json_type),
    Column("audiences_json", json_type),
    Column("dominant_intents_json", json_type),
    Column("source_mix_json", json_type),
    Column("confidence", Float),
    Column("freshness", Float),
    Column("velocity", Float),
    Column("novelty", Float),
    Column("relevance", Float),
    Column("saturation", Float),
    Column("opportunity_score", Float),
    Column("signal_ids_json", json_type),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_market_topic_clusters_workspace", "workspace_id", "opportunity_score"),
    Index("idx_market_topic_clusters_run", "run_id"),
)

market_opportunity_candidates = Table(
    "market_opportunity_candidates",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("market_intelligence_runs.id", ondelete="CASCADE")),
    Column("cluster_id", String, ForeignKey("market_topic_clusters.id", ondelete="SET NULL")),
    Column("title", Text, nullable=False),
    Column("topic", Text, nullable=False),
    Column("target_keyword", Text),
    Column("content_format", String),
    Column("editorial_angle", Text),
    Column("audience", Text),
    Column("intent", String),
    Column("action_hint", String, nullable=False),
    Column("confidence", Float),
    Column("evidence_summary", Text),
    Column("source_signal_ids_json", json_type),
    Column("risk_json", json_type),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_market_opportunity_candidates_workspace", "workspace_id", "confidence"),
    Index("idx_market_opportunity_candidates_run", "run_id"),
)

editorial_generation_runs = Table(
    "editorial_generation_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("market_run_id", String, ForeignKey("market_intelligence_runs.id", ondelete="SET NULL")),
    Column("status", String, nullable=False),
    Column("started_at", String, nullable=False),
    Column("completed_at", String),
    Column("seeds_processed", Integer, nullable=False, server_default=text("0")),
    Column("concepts_created", Integer, nullable=False, server_default=text("0")),
    Column("finalists_created", Integer, nullable=False, server_default=text("0")),
    Column("warnings_json", json_type),
    Column("error_message", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_editorial_generation_runs_workspace", "workspace_id", "created_at"),
)

editorial_opportunity_concepts = Table(
    "editorial_opportunity_concepts",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("editorial_generation_runs.id", ondelete="CASCADE")),
    Column("seed_candidate_id", String, ForeignKey("market_opportunity_candidates.id", ondelete="CASCADE")),
    Column("cluster_id", String, ForeignKey("market_topic_clusters.id", ondelete="SET NULL")),
    Column("title", Text, nullable=False),
    Column("topic", Text, nullable=False),
    Column("content_type", String, nullable=False),
    Column("audience", Text),
    Column("intent", String),
    Column("angle", Text),
    Column("confidence", Float),
    Column("novelty", Float),
    Column("authority_value", Float),
    Column("evidence_summary", Text),
    Column("source_signal_ids_json", json_type),
    Column("target_keyword", Text),
    Column("action_hint", String, nullable=False),
    Column("related_content_ids_json", json_type),
    Column("is_finalist", Integer, nullable=False, server_default=text("0")),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_editorial_opportunity_concepts_workspace", "workspace_id", "is_finalist"),
    Index("idx_editorial_opportunity_concepts_seed", "seed_candidate_id"),
    Index("idx_editorial_opportunity_concepts_run", "run_id"),
)

content_entities = Table(
    "content_entities",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("post_id", String),
    Column("job_id", String),
    Column("content_plan_item_id", String),
    Column("entity", Text, nullable=False),
    Column("entity_type", String),
    Column("confidence", Float),
    Column("source", String),
    Column("created_at", String, nullable=False),
    Index("idx_content_entities_workspace", "workspace_id"),
    Index("idx_content_entities_entity", "entity"),
)

content_clusters = Table(
    "content_clusters",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("post_id", String),
    Column("job_id", String),
    Column("content_plan_item_id", String),
    Column("cluster", Text, nullable=False),
    Column("confidence", Float),
    Column("source", String),
    Column("created_at", String, nullable=False),
    Index("idx_content_clusters_workspace", "workspace_id"),
    Index("idx_content_clusters_cluster", "cluster"),
)

content_coverage = Table(
    "content_coverage",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("coverage_type", String, nullable=False),
    Column("name", Text, nullable=False),
    Column("coverage_score", Float),
    Column("freshness_score", Float),
    Column("content_count", Integer, nullable=False, server_default=text("0")),
    Column("published_count", Integer, nullable=False, server_default=text("0")),
    Column("draft_count", Integer, nullable=False, server_default=text("0")),
    Column("gap_score", Float),
    Column("saturation_score", Float),
    Column("cannibalization_risk", Float),
    Column("duplicate_topic_risk", Float),
    Column("refresh_score", Float),
    Column("refresh_candidate", Boolean, nullable=False, server_default=false()),
    Column("refresh_reason", Text),
    Column("last_published", String),
    Column("last_updated", String),
    Column("last_major_update", String),
    Column("metadata_json", json_type),
    Column("updated_at", String, nullable=False),
    Index("idx_content_coverage_workspace", "workspace_id"),
    Index("idx_content_coverage_type_name", "workspace_id", "coverage_type", "name"),
)

content_plans = Table(
    "content_plans",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("analysis_job_id", String, ForeignKey("analysis_jobs.id", ondelete="SET NULL")),
    Column("name", Text, nullable=False),
    Column("cadence", String, nullable=False),
    Column("publish_policy", String, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("status", String, nullable=False, server_default=text("'draft'")),
    Column("summary", Text),
    Column("plan_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_content_plans_workspace", "workspace_id"),
)

content_plan_items = Table(
    "content_plan_items",
    metadata,
    Column("id", String, primary_key=True),
    Column("content_plan_id", String, ForeignKey("content_plans.id", ondelete="CASCADE"), nullable=False),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("opportunity_id", String, ForeignKey("opportunities.id", ondelete="SET NULL")),
    Column("trend_signal_id", String, ForeignKey("trend_signals.id", ondelete="SET NULL")),
    Column("generated_job_id", String),
    Column("published_content_id", String),
    Column("sequence_index", Integer, nullable=False),
    Column("scheduled_for", String),
    Column("state", String, nullable=False, server_default=text("'planned'")),
    Column("content_role", String),
    Column("title", Text, nullable=False),
    Column("target_keyword", Text),
    Column("audience", Text),
    Column("notes", Text),
    Column("policy", String),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_content_plan_items_plan", "content_plan_id"),
    Index("idx_content_plan_items_workspace_state", "workspace_id", "state"),
    Index("idx_content_plan_items_scheduled", "scheduled_for"),
)

published_content = Table(
    "published_content",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("job_id", String),
    Column("content_plan_item_id", String),
    Column("external_id", Text),
    Column("url", Text),
    Column("title", Text),
    Column("status", String, nullable=False),
    Column("channel", String, nullable=False, server_default=text("'wordpress'")),
    Column("clusters_json", json_type),
    Column("metrics_json", json_type),
    Column("published_at", String),
    Column("last_checked_at", String),
    Column("refresh_after", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_published_content_workspace", "workspace_id"),
    Index("idx_published_content_external", "external_id"),
)

reassessment_runs = Table(
    "reassessment_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("status", String, nullable=False),
    Column("summary", Text),
    Column("strategy_adjustments_json", json_type),
    Column("new_opportunities_json", json_type),
    Column("retired_opportunities_json", json_type),
    Column("recommended_refreshes_json", json_type),
    Column("calendar_diff_json", json_type),
    Column("provider_status_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_reassessment_runs_workspace", "workspace_id"),
)

provider_status = Table(
    "provider_status",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE")),
    Column("provider_name", String, nullable=False),
    Column("provider_type", String, nullable=False),
    Column("status", String, nullable=False),
    Column("capabilities_json", json_type),
    Column("last_error", Text),
    Column("last_checked_at", String),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_provider_status_workspace", "workspace_id"),
    Index("idx_provider_status_provider", "provider_name", "provider_type"),
)

approval_events = Table(
    "approval_events",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("content_plan_item_id", String, ForeignKey("content_plan_items.id", ondelete="SET NULL")),
    Column("event_type", String, nullable=False),
    Column("actor", String, nullable=False, server_default=text("'user'")),
    Column("notes", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_approval_events_workspace", "workspace_id"),
    Index("idx_approval_events_item", "content_plan_item_id"),
)

workspace_content_inventory = Table(
    "workspace_content_inventory",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("url", Text, nullable=False),
    Column("canonical_url", Text, nullable=False),
    Column("title", Text),
    Column("slug", String),
    Column("content_type", String, nullable=False, server_default=text("'unknown'")),
    Column("source", String, nullable=False, server_default=text("'existing_site'")),
    Column("wordpress_post_id", String),
    Column("created_by_trendplot", Boolean, nullable=False, server_default=text("false")),
    Column("generated_job_id", String),
    Column("published_at", String),
    Column("last_seen_at", String, nullable=False),
    Column("topic_fingerprint", Text),
    Column("coverage_topics_json", json_type),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_workspace_content_inventory_workspace", "workspace_id"),
    Index("idx_workspace_content_inventory_canonical", "workspace_id", "canonical_url"),
    Index("idx_workspace_content_inventory_fingerprint", "workspace_id", "topic_fingerprint"),
)

ai_editorial_strategist_runs = Table(
    "ai_editorial_strategist_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("status", String, nullable=False),
    Column("started_at", String, nullable=False),
    Column("completed_at", String),
    Column("ideas_created", Integer, nullable=False, server_default=text("0")),
    Column("warnings_json", json_type),
    Column("error_message", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_ai_editorial_strategist_runs_workspace", "workspace_id", "created_at"),
)

ai_editorial_strategist_ideas = Table(
    "ai_editorial_strategist_ideas",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("ai_editorial_strategist_runs.id", ondelete="CASCADE")),
    Column("title", Text, nullable=False),
    Column("topic", Text, nullable=False),
    Column("idea_type", String, nullable=False),
    Column("entity", Text),
    Column("rationale", Text),
    Column("priority", String),
    Column("target_keyword", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_ai_editorial_strategist_ideas_workspace", "workspace_id"),
    Index("idx_ai_editorial_strategist_ideas_run", "run_id"),
)

ai_opportunity_ideation_runs = Table(
    "ai_opportunity_ideation_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("status", String, nullable=False),
    Column("started_at", String, nullable=False),
    Column("completed_at", String),
    Column("opportunities_created", Integer, nullable=False, server_default=text("0")),
    Column("warnings_json", json_type),
    Column("error_message", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_ai_opportunity_ideation_runs_workspace", "workspace_id", "created_at"),
)

ai_opportunity_ideation_opportunities = Table(
    "ai_opportunity_ideation_opportunities",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("ai_opportunity_ideation_runs.id", ondelete="CASCADE")),
    Column("headline", Text, nullable=False),
    Column("abstract", Text, nullable=False),
    Column("search_intent", String, nullable=False),
    Column("content_type", String, nullable=False),
    Column("recommendation_type", String, nullable=False, server_default=text("'create'")),
    Column("related_products_json", json_type),
    Column("related_topics_json", json_type),
    Column("target_audience", Text),
    Column("priority_reason", Text),
    Column("safety_notes_json", json_type),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_ai_opportunity_ideation_opportunities_workspace", "workspace_id"),
    Index("idx_ai_opportunity_ideation_opportunities_run", "run_id"),
)

ai_recommendation_review_runs = Table(
    "ai_recommendation_review_runs",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("status", String, nullable=False),
    Column("started_at", String, nullable=False),
    Column("completed_at", String),
    Column("items_reviewed", Integer, nullable=False, server_default=text("0")),
    Column("warnings_json", json_type),
    Column("error_message", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Column("updated_at", String, nullable=False),
    Index("idx_ai_recommendation_review_runs_workspace", "workspace_id", "created_at"),
)

ai_recommendation_reviews = Table(
    "ai_recommendation_reviews",
    metadata,
    Column("id", String, primary_key=True),
    Column("workspace_id", String, ForeignKey("autopilot_workspaces.id", ondelete="CASCADE"), nullable=False),
    Column("run_id", String, ForeignKey("ai_recommendation_review_runs.id", ondelete="CASCADE")),
    Column("recommendation_id", String, nullable=False),
    Column("relevance_score", Float),
    Column("business_alignment_score", Float),
    Column("niche_alignment_score", Float),
    Column("content_usefulness_score", Float),
    Column("recommended_action", String, nullable=False),
    Column("reason", Text),
    Column("metadata_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_ai_recommendation_reviews_run", "run_id"),
    Index("idx_ai_recommendation_reviews_recommendation", "recommendation_id"),
)

connector_events = Table(
    "connector_events",
    metadata,
    Column("id", String, primary_key=True),
    Column("site_id", String, nullable=False),
    Column("event_id", String, nullable=False),
    Column("event_type", String, nullable=False),
    Column("workspace_id", String),
    Column("occurred_at", String, nullable=False),
    Column("source", String),
    Column("post_json", json_type),
    Column("payload_json", json_type),
    Column("created_at", String, nullable=False),
    Index("idx_connector_events_site_event", "site_id", "event_id"),
    Index("idx_connector_events_workspace", "workspace_id"),
    Index("idx_connector_events_type", "event_type"),
)
