from app.opportunities.verticals.base import VerticalProfile


GENERIC_PROFILE = VerticalProfile(
    id="generic",
    name="Generic",
    description="Vertical-neutral opportunity intelligence with no domain-specific assumptions.",
    boilerplate_hints={
        "account",
        "affiliate",
        "billing",
        "cart",
        "checkout",
        "contact",
        "delivery",
        "disclaimer",
        "footer",
        "guarantee",
        "login",
        "policy",
        "privacy",
        "refund",
        "returns",
        "shipping",
        "terms",
        "track",
        "why choose",
        "why us",
    },
    product_path_hints={"product", "products", "collection", "collections", "category", "shop", "store", "services"},
    educational_hints={"blog", "learn", "guide", "resources", "faq", "glossary", "academy", "help"},
    concept_hints={
        "comparison",
        "care",
        "maintenance",
        "beginner",
        "trends",
        "sourcing",
        "use cases",
        "troubleshooting",
        "glossary",
        "questions",
    },
    adjacent_niche_map={
        "product": ["buying context", "comparison education", "care and maintenance"],
        "service": ["use cases", "implementation", "buyer education"],
        "category": ["category guides", "trend coverage", "comparison pages"],
    },
    compliance_profile={
        "rules": ["Do not invent business facts, certifications, prices, warranties, or guarantees."],
    },
    opportunity_type_weights={
        "product_deep_dive": 1.0,
        "comparison_article": 1.0,
        "beginner_education": 0.9,
        "buyer_guide": 0.9,
        "glossary": 0.8,
        "faq_cluster": 0.9,
        "category_guide": 0.9,
        "trend_article": 0.7,
        "care_maintenance": 0.6,
        "use_case": 0.7,
        "competitor_gap_article": 0.8,
    },
    title_style_guidance=[
        "Use precise, editorial titles tied to the niche signals.",
        "Avoid repetitive generic guide phrasing when a more specific angle exists.",
    ],
    image_allowed_types=[
        "featured_editorial_image",
        "product_context_image",
        "lifestyle_image",
        "comparison_visual",
        "process_workflow_visual",
        "concept_map",
        "checklist_graphic",
        "diagram",
        "table_infographic",
        "trend_visual",
        "brand_safe_abstract_visual",
    ],
    image_avoid_rules=[
        "Avoid misleading imagery or unsupported product claims.",
        "Avoid fake logos, fake brands, fake certifications, and deceptive seals.",
        "Avoid deceptive before/after imagery.",
        "Avoid unsafe use of products.",
        "Avoid visuals implying outcomes not supported by the article.",
        "Avoid copyrighted or trademark-infringing style requests.",
    ],
    image_style_guidance=[
        "Use brand-safe editorial visuals grounded in the article topic.",
        "Prefer clean, useful visuals over decorative filler.",
    ],
    featured_image_preferences=["Use one broad editorial visual when it helps summarize the article."],
    inline_image_preferences=[
        "Use inline visuals only where they clarify a comparison, process, concept, trend, or product context.",
        "Avoid placing visuals in FAQ, references, legal, or disclaimer sections.",
    ],
    unsafe_visual_concepts=["fake logo", "fake certification", "before and after", "misleading results", "unsafe product use"],
    preferred_visual_contexts=["comparison", "process", "concept", "trend", "product context", "checklist"],
)
