from app.opportunities.verticals.base import VerticalProfile


PEPTIDES_PROFILE = VerticalProfile(
    id="peptides",
    name="Peptides / Research Compounds",
    description="Research-use peptide and compound intelligence with conservative RUO framing.",
    domain_keywords={"peptide", "peptides", "research peptide", "compound", "lyophilized", "ruo"},
    educational_hints={"blog", "learn", "guide", "research", "science", "resources", "faq", "glossary", "protocol"},
    known_entities={
        "5-amino-1mq",
        "aicar",
        "bpc-157",
        "cjc-1295",
        "dsip",
        "epitalon",
        "ghk-cu",
        "glp-1",
        "glutathione",
        "humanin",
        "ipamorelin",
        "mots-c",
        "nad+",
        "selank",
        "semax",
        "shlp",
        "shlps",
        "ss-31",
        "tb-500",
        "tesamorelin",
    },
    mechanism_hints={
        "ampk",
        "angiogenesis",
        "autophagy",
        "bioenergetics",
        "cellular stress",
        "exercise adaptation",
        "glucose metabolism",
        "inflammation",
        "insulin signaling",
        "metabolic flexibility",
        "metabolic signaling",
        "mitochondria",
        "mitochondrial function",
        "oxidative stress",
        "senescence",
        "stability",
        "tissue repair",
    },
    concept_hints={
        "biohacking",
        "comparison",
        "experimental design",
        "glossary",
        "lab handling",
        "lab reproducibility",
        "longevity",
        "mechanism",
        "myths",
        "peptide purity",
        "peptide storage",
        "recovery",
        "research methods",
        "sourcing ethics",
        "translational science",
    },
    entity_expansion_map={
        "mots-c": ["mitochondria", "AMPK", "metabolic signaling", "exercise adaptation", "insulin signaling", "oxidative stress", "mitochondrial peptides", "aging research"],
        "bpc-157": ["recovery discussions", "angiogenesis", "tissue repair", "laboratory myths", "peptide handling", "comparison discussions"],
        "tb-500": ["recovery discussions", "actin", "cell migration", "peptide handling", "comparison discussions"],
        "ghk-cu": ["copper peptides", "skin research", "matrix remodeling", "cosmetic research", "peptide stability"],
        "nad+": ["mitochondria", "bioenergetics", "aging research", "metabolic health research", "cellular stress"],
        "ampk": ["metabolic signaling", "exercise adaptation", "glucose metabolism", "mitochondria", "cellular energy"],
    },
    product_family_map={
        "mitochondrial peptides": {"mots-c", "humanin", "shlp", "shlps", "ss-31"},
        "recovery peptides": {"bpc-157", "tb-500"},
        "copper peptides": {"ghk-cu"},
        "metabolic research compounds": {"aicar", "5-amino-1mq", "tesamorelin", "nad+"},
        "sleep and neuropeptides": {"dsip", "selank", "semax"},
    },
    adjacent_niche_map={
        "peptide": ["longevity research", "lab reproducibility", "peptide storage", "peptide purity", "research methods"],
        "mots-c": ["mitochondrial biology", "metabolic signaling", "exercise adaptation"],
        "bpc-157": ["recovery research", "angiogenesis discussions", "laboratory myths"],
    },
    audience_examples=[
        {
            "name": "Research-first peptide shoppers",
            "description": "Readers comparing entities, mechanisms, handling, and documentation before evaluating catalog pages.",
            "audience_type": "research_commercial",
            "expertise_level": "intermediate",
            "confidence": 0.82,
            "commercial_intent": 0.55,
            "research_intent": 0.92,
            "concerns": ["RUO framing", "storage", "purity", "unsupported claims"],
            "recurring_questions": ["How do related peptides differ?", "What handling context matters?"],
            "preferred_content_types": ["mechanism explainers", "comparisons", "glossaries", "FAQ clusters"],
            "authority_topics": ["mechanisms", "product families", "lab handling"],
            "related_entities": ["peptides", "research compounds"],
        }
    ],
    compliance_profile={
        "requires_ruo_framing": True,
        "biomedical_keyword_hints": [
            "peptide",
            "lyophilized",
            "reconstitution",
            "bpc",
            "tb-500",
            "ghk",
        ],
        "ideation_themes": [
            "reconstitution",
            "storage",
            "handling",
            "stability",
            "concentration",
            "lab calculations",
            "comparison articles",
            "FAQ and guide articles",
        ],
        "rules": [
            "Use research-use-only framing.",
            "Do not make therapeutic, dosing, diagnostic, treatment, or human-use claims.",
            "Avoid implying clinical outcomes or human consumption.",
        ],
        "risk": "high",
    },
    opportunity_type_weights={
        "mechanism_explainer": 1.2,
        "comparison_article": 1.1,
        "faq_cluster": 1.0,
        "glossary": 1.0,
        "laboratory_practice": 1.1,
        "myth_vs_fact": 1.0,
        "geo_search": 1.0,
    },
    title_style_guidance=[
        "Use cautious research-context language.",
        "Avoid dosing, effects, treatment, and human-use phrasing.",
    ],
    image_allowed_types=[
        "abstract_scientific_editorial_image",
        "mechanism_diagram",
        "lab_neutral_visual",
        "product_neutral_research_visual",
        "concept_map",
    ],
    image_avoid_rules=[
        "Avoid injections, syringes, vials being used on humans, and human consumption.",
        "Avoid doctors treating patients, clinical treatment scenes, and medical benefit implication.",
        "Avoid before/after body imagery and therapeutic outcomes.",
    ],
    image_style_guidance=[
        "Use neutral research visuals with no human-use implication.",
        "Prefer abstract mechanism, concept, or documentation visuals over product-use scenes.",
    ],
    featured_image_preferences=["Product-neutral research editorial visual with abstract scientific elements."],
    inline_image_preferences=["Use mechanism diagrams or concept maps for research-context sections."],
    unsafe_visual_concepts=["syringe", "injection", "doctor treating", "patient", "human consumption", "clinical treatment", "medical benefit"],
    preferred_visual_contexts=["mechanism", "research context", "comparison", "concept map", "lab-neutral documentation"],
)
